import React from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import styles from './page.module.css';

export default function TermsPage() {
  return (
    <main className={styles.main}>
      <Navbar />
      <div className={styles.container}>
        <div className={styles.content}>
          <h1 className={styles.title}>Terms and Conditions</h1>
          <h1 className={styles.title}>About these Terms</h1>
          <p className={styles.paragraph}>These Terms govern purchases of products and installation services made through the BexaVolt website. Please read them carefully before placing an order.</p>
          <p className={styles.paragraph}>Important information before you order</p>
          <p className={styles.paragraph}>Introduction</p>
          <p className={styles.paragraph}>(a) This website (Site) is operated by Oztronica Pty Ltd trading as BexaVolt (ABN 46 943 680 088) (we, us or our). These terms and conditions (Terms) are between us and you, the person placing an order for products or services through the Site.</p>
          <p className={styles.paragraph}>- Use of the Site</p>
          <p className={styles.paragraph}>You accept these Terms by placing an order via the Site.</p>
          <p className={styles.paragraph}>You must not use the Site and/or place an order for products through the Site unless you are at least 18 years old.</p>
          <p className={styles.paragraph}>When using the Site, you must not do or attempt to do anything that is unlawful or inappropriate, including:</p>
          <p className={styles.paragraph}>anything that would constitute a breach of an individual’s privacy including uploading private or personal information without an individual’s consent) or any other legal rights;</p>
          <p className={styles.paragraph}>using the Site to defame, harass, threaten, menace or offend any person;</p>
          <p className={styles.paragraph}>using the Site for unlawful purposes;</p>
          <p className={styles.paragraph}>interfering with any user of the Site;</p>
          <p className={styles.paragraph}>tampering with or modifying the Site (including by transmitting viruses and using trojan horses);</p>
          <p className={styles.paragraph}>using the Site to send unsolicited electronic messages;</p>
          <p className={styles.paragraph}>using data mining, robots, screen scraping or similar data gathering and extraction tools on the Site; or</p>
          <p className={styles.paragraph}>facilitating or assisting a third party to do any of the above acts.</p>
          <p className={styles.paragraph}>3 - Orders</p>
          <p className={styles.paragraph}>You may order products from us as set out on the Site. If you place an order for products on our Site, you are making an order to purchase the product(s) for the price listed on the Site (including the delivery fees or other applicable charges and taxes).</p>
          <p className={styles.paragraph}>We may, at our absolute discretion, accept or reject an order. If we need to reject your order, we will notify you within a reasonable time after your order is placed. Once we accept an order, a binding agreement is formed for the supply of products to you in accordance with these Terms.</p>
          <p className={styles.paragraph}>It is your responsibility to check the order details, including selected products, delivery details and pricing, before you submit your order through the Site.</p>
          <p className={styles.paragraph}>When you order and pay on the Site and your payment has been validated, we will provide you with an order confirmation email, which may include an order number, an order ID, the delivery and billing addresses and a description of what was ordered.</p>
          <p className={styles.paragraph}>Where you have purchased installation services as part of your order, our team will contact you to arrange the installation services. You agree to provide us (and our Personnel) with access to the premises where the product is to be installed (and any facilities at the premises) as is reasonably necessary for us to provide the installation services, free from harm or risk to health or safety, at the times and on the dates reasonably requested by us or as agreed between the Parties. You acknowledge and agree that you may be required to pay our additional costs reasonably incurred because of you failing to comply with this clause.</p>
          <p className={styles.paragraph}>All purchases made through the Site are subject to availability. We do our best to keep products in stock and to keep the Site up to date with the availability of products.</p>
          <p className={styles.paragraph}>If a product is available for back-order, or pre-order only (it is not currently in stock), this will be clearly indicated on our Site. We may display the date that the product is expected to be available for dispatch to you. These dates are approximation only, and we will not be liable for any delay in the product being available for dispatch or the inaccuracy of the date.</p>
          <p className={styles.paragraph}>We may cancel, at any time before delivery and for whatever reason, an order that we have previously accepted, including where there is a considerable delay in dispatching your order, if for any reason we cannot supply the products you order (for example for an event beyond our reasonable control) or if products ordered were subject to an error on our Site (for example in relation to a description, price or image). We will contact you using the details you provided when you placed your order.</p>
          <p className={styles.paragraph}>4 - Price and payments</p>
          <p className={styles.paragraph}>You must pay us the purchase price of each product you order, plus any applicable delivery costs as set out on the Site (the Price) in accordance with this clause. All amounts are stated in Australian dollars and Australian GST (where applicable) will be set out separately.</p>
          <p className={styles.paragraph}>You must pay the Price upfront using one of the methods set out on the Site.</p>
          <p className={styles.paragraph}>You must not pay, or attempt to pay, the Price by fraudulent or unlawful means. If you make a payment by debit card or credit card, you warrant that you are authorised to use the debit card or credit card to make the payment.</p>
          <p className={styles.paragraph}>Where you order the products for delivery outside Australia, you may need to pay customs duties or taxes in addition to the Price.</p>
          <p className={styles.paragraph}>We may from time-to-time issue promotional discount codes for certain products on the Site.</p>
          <p className={styles.paragraph}>To claim the discount, you must enter the promotional discount code at the time of submitting your order through the Site.</p>
          <p className={styles.paragraph}>BexaVolt retains ownership of any unit that has not been paid in full. For example, where a deposit has been made or where only partial payment of the invoice has occurred.</p>
          <p className={styles.paragraph}>Best Price Guarantee does not apply to products from the following Agency brands: Tesla, Schneider, KEBA, Fronius & Delta due to RRP set by manufacturers.</p>
          <p className={styles.paragraph}>5 -  Delivery, title and risk</p>
          <p className={styles.paragraph}>If possible, we will deliver the products to the delivery address you provide when making your order. We currently deliver to areas as set out on the Site. Please refer to the delivery information on the Site to ensure you are in our delivery area. If you are not in our delivery area, please contact us to discuss delivery options.</p>
          <p className={styles.paragraph}>We normally dispatch products within 24 business hours of receiving an order, unless otherwise noted on the Site. All delivery periods displayed on the Site are estimates only, based on the information provided by the delivery company.</p>
          <p className={styles.paragraph}>If you choose to collect your products from our warehouse, we will notify you via email when your products are ready for collection (Collection Notification). You agree to collect your products from the collection location notified in the Collection Notification within 30 days of the date of the Collection Notification. If you fail to collect your products within the agreed period, you acknowledge and agree that we may cancel your order and return your products to our inventory and make those products available for sale to other customers. We will provide you with a refund of the Price paid by you where we cancel your order in accordance with this clause.</p>
          <p className={styles.paragraph}>If you need to change the delivery day or delivery address, please notify us immediately in writing.</p>
          <p className={styles.paragraph}>We deliver the products using a range of delivery methods. You may need to sign for some deliveries. If neither you nor your authorised representative is at the delivery address to accept delivery, you agree that we may leave the products at your premises</p>
          <p className={styles.paragraph}>Title of the products will remain with us until you have paid the Price in full for the products. Until title passes, you must not do anything which seeks to create an encumbrance, lien, charge or other interest in or over the products.</p>
          <p className={styles.paragraph}>Risk in the products will pass to you as soon as they are delivered to the delivery address you provided in your order, or if you have chosen to collect your order, as soon as you collect your products from the collection location.</p>
          <p className={styles.paragraph}>6 - Warranty against defects</p>
          <p className={styles.paragraph}>In Australia, our goods come with guarantees which cannot be excluded under the Australian Consumer Law. You are entitled to a replacement or refund for a major failure and compensation for any other reasonably foreseeable loss or damage. You are also entitled to have the goods repaired or replaced if the goods fail to be of acceptable quality and the failure does not amount to a major failure.</p>
          <p className={styles.paragraph}>In addition to any other rights, you may have under the Australian Consumer Law we warrant to you that the product we supply to you will be free from defects for the period of time set out in the warranty documentation supplied with the product (Warranty).</p>
          <p className={styles.paragraph}>What is a defect? Our Warranty applies to any fault, error or defects in the products arising because of improper workmanship or materials (Defect).</p>
          <p className={styles.paragraph}>What do you need to do to claim the Warranty? Within the warranty period, if you believe you have a product the subject of a Defect you must cease using the product and contact us in writing along with photo and/or video evidence and description of the Defect. If we ask you to, you must return to us the defective products, together with all packaging, parts, accessories, documentation and proof of purchase, to the contact details set out below.</p>
          <p className={styles.paragraph}>Where you return a product as part of a Defect claim you will need to cover any associated costs of you returning the products to us and where we find the product is covered by our Warranty, we will refund the associated costs of you returning the product to us.</p>
          <p className={styles.paragraph}>When we receive the products you return, we will assess the alleged Defect and decide as to whether the claim is valid under our Warranty.</p>
          <p className={styles.paragraph}>What will we do if you make a successful claim under our Warranty? We will, at our own cost:</p>
          <p className={styles.paragraph}>repair or replace the product (the decision of whether to repair or replace is at our sole discretion); or</p>
          <p className={styles.paragraph}>if we are unable to repair or replace the product, we will offer you a choice of credit, refund or compensation as applicable to the Defect.</p>
          <p className={styles.paragraph}>Damage Not covered by our Warranty. The Warranty does not cover any Defect which is caused (or partly caused) or contributed to, by any:</p>
          <p className={styles.paragraph}>reasonable wear and tears;</p>
          <p className={styles.paragraph}>act or omission, accident, or negligence by you or any third party not engaged by us (including any third-party installer of the product);</p>
          <p className={styles.paragraph}>failure on your part to follow any instructions or guidelines (including any manual) provided by us or the manufacturer in relation to the product;</p>
          <p className={styles.paragraph}>use of the product other than for any application or use specified by us or the manufacturer;</p>
          <p className={styles.paragraph}>continued use of your product (where such use is not reasonable) after any defect in your product becomes apparent or would have become apparent to a reasonably prudent person;</p>
          <p className={styles.paragraph}>incorporation or installation of fixtures, appliances or other items into your product;</p>
          <p className={styles.paragraph}>failure by you to notify us of any defect in your product within a reasonable period after you become aware of or ought to have reasonably become aware of the relevant defect; or</p>
          <p className={styles.paragraph}>installation, repair, replacement, maintenance, altering, overhauling or otherwise compromising the product by you or any person other than us or the manufacturer.</p>
          <p className={styles.paragraph}>7 - Australian Consumer Law</p>
          <p className={styles.paragraph}>We do not accept returns for change of mind or other circumstances. However, you may have rights to a repair, replacement or refund under the Australian Consumer Law.</p>
          <p className={styles.paragraph}>Nothing in these Terms attempts to modify or exclude the conditions, warranties and undertakings, and other legal rights, under the Australian Consumer Law (Consumer Law Rights). Any and all other warranties or conditions which are not guaranteed by the Australian Consumer Law are expressly excluded where permitted, except to the extent such warranties and conditions are fully expressed in these Terms.</p>
          <p className={styles.paragraph}>Where you return products to us to seek an Australian Consumer Law remedy, you will need to cover any associated costs (for example delivery costs) of you returning the products to us.</p>
          <p className={styles.paragraph}>Where your claim is a valid claim under the Australian Consumer Law, we will refund your return delivery costs and, depending on the failure, either dispatch a new or repaired replacement product or refund you the Price of the relevant product. Please contact us for further information.</p>
          <p className={styles.paragraph}>8 - Limitations</p>
          <p className={styles.paragraph}>Despite anything to the contrary, but subject to your Consumer Law Rights, to the maximum extent permitted by law:</p>
          <p className={styles.paragraph}>neither Party will be liable for Consequential Loss;</p>
          <p className={styles.paragraph}>Each Party’s liability for any Liability under these Terms will be reduced proportionately to the extent the relevant Liability was caused or contributed to by the acts or omissions of the other Party, including any failure by that Party to mitigate its losses; and</p>
          <p className={styles.paragraph}>our aggregate liability for any Liability arising from or in connection with the Terms (including the products and/or the subject matter of the Terms) will be limited to, and must not exceed, the portion of the Price paid by you to us for the products the subject of the relevant claim.</p>
          <p className={styles.paragraph}>9 - Intellectual property</p>
          <p className={styles.paragraph}>You acknowledge and agree that any intellectual property (including copyright and trademarks) developed, adapted, modified or created by us or our personnel (including in connection with the Terms, any content on the Site, and the products) (Our Intellectual Property) will at all times vest, or remain vested, in us.</p>
          <p className={styles.paragraph}>We authorise you to use Our Intellectual Property solely for your own personal use, and in the manner in which it was intended to be used.</p>
          <p className={styles.paragraph}>You must not, without our prior written consent:</p>
          <p className={styles.paragraph}>copy, in whole or in part, any of Our Intellectual Property;</p>
          <p className={styles.paragraph}>reproduce, retransmit, distribute, disseminate, sell, publish, broadcast or circulate any of Our Intellectual Property to any third party; or</p>
          <p className={styles.paragraph}>breach any intellectual property rights connected with the Site or the products, including (without limitation) altering or modifying any of Our Intellectual Property; causing any of Our Intellectual Property to be framed or embedded in another website; or creating derivative works from any of Our Intellectual Property.</p>
          <p className={styles.paragraph}>d). Nothing in the above clause restricts your ability to publish, post or repost Our Intellectual Property on your social media page or blog, provided that:</p>
          <p className={styles.paragraph}>you do not assert that you are the owner of Our Intellectual Property;</p>
          <p className={styles.paragraph}>unless explicitly agreed by us in writing, you do not assert that you are endorsed or approved by us;</p>
          <p className={styles.paragraph}>you do not damage or take advantage of our reputation, including in a manner that is illegal, unfair, misleading or deceptive; and</p>
          <p className={styles.paragraph}>you comply with all other terms of these Terms.</p>
          <p className={styles.paragraph}>10 - Content you upload</p>
          <p className={styles.paragraph}>We encourage you to interact with the Site and with us on social media! You may be permitted to post, upload, publish, submit or transmit relevant information and content (User Content) on the Site. We may run campaigns via the Site and via social media that encourage you to post User Content on social media using specific hashtags (#) (Tag).</p>
          <p className={styles.paragraph}>If you make any User Content available on or through the Site, including on social media using a Tag, you grant to us a worldwide, irrevocable, perpetual, non-exclusive, transferable, royalty-free licence to use the User Content, with the right to use, view, copy, adapt, modify, distribute, license, transfer, communicate, publicly display, publicly perform, transmit, broadcast, access, or otherwise exploit such User Content on, through or by means of the Site and our social media platforms.</p>
          <p className={styles.paragraph}>You agree that you are solely responsible for all User Content that you make available on or through the Site, including on social media using a Tag. You represent and warrant that:</p>
          <p className={styles.paragraph}>you are either the sole and exclusive owner of all User Content, or you have all rights, licences, consents and releases that are necessary to grant to us the rights in such User Content (as contemplated by these Terms); and</p>
          <p className={styles.paragraph}>neither the User Content nor the posting, uploading, publication, submission or transmission of the User Content or our use of the User Content on, through or by means of our Site (including on social media) will infringe, misappropriate or violate a third party’s intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.</p>
          <p className={styles.paragraph}>We do not endorse or approve, and are not responsible for, any User Content. We may, at any time (at our sole discretion), remove any User Content.</p>
          <p className={styles.paragraph}>11 - General</p>
          <p className={styles.paragraph}>Disputes: A Party may not commence court proceedings relating to a dispute without first meeting with the other Party to seek (in good faith) to resolve the dispute, failing which the Parties agree to engage a mediator to attempt to resolve the dispute. The costs of the mediation will be shared equally between the Parties. Nothing in this clause will operate to prevent a Party from seeking urgent injunctive or equitable relief from a court of appropriate jurisdiction.</p>
          <p className={styles.paragraph}>Notices: Any notice given under these Terms must be in writing addressed to us at the details set out below or to you at the details provided when you submitted your order or in your account. Any notice may be sent by standard post or email and will be deemed to have been served on the expiry of 48 hours in the case of post, or at the time of transmission in the case of transmission by email.</p>
          <p className={styles.paragraph}>Privacy: We agree to comply with the legal requirements of the Australian Privacy Principles as set out in the Privacy Act 1988 (Cth) and any other applicable legislation or privacy guidelines. We will handle all personal information that we receive in accordance with our Privacy Policy, available at https://www.BexaVolt.com.au/privacy-policy/</p>
          <p className={styles.paragraph}>Force Majeure: Neither Party will be liable for any delay or failure to perform their respective obligations under these Terms if such delay or failure is caused or contributed to by a Force Majeure Event, provided the Party seeking to rely on the benefit of this clause, as soon as reasonably practical, notified the other Party in writing about the Force Majeure Event and the extent to which it is unable to perform its obligations and uses reasonable endeavours to minimise the duration and adverse consequences of the Force Majeure Event.</p>
          <p className={styles.paragraph}>Feedback and complaints: We are always looking to improve our services. If you have any feedback or complaint, please notify us of our contact details below and we will take reasonable steps to address any concerns you have.</p>
          <p className={styles.paragraph}>Assignment: You must not assign any rights or obligations under these Terms, whether in whole or in part, without our prior written consent.</p>
          <p className={styles.paragraph}>Governing law: These Terms are governed by the laws of New South Wales. Each Party irrevocably and unconditionally submits to the exclusive jurisdiction of the courts operating in New South Wales and any courts entitled to hear appeals from those courts and waives any right to object to proceedings being brought in those courts.</p>
          <p className={styles.paragraph}>Third party sites: The Site may contain links to websites operated by third parties. Unless we tell you otherwise, we do not control, endorse or approve, and are not responsible for, the content on those websites. We recommend that you make your own investigations with respect to the suitability of those websites. If you purchase goods or services from a third-party website linked from the Site, such third party provides the goods and services to you, not us.</p>
          <p className={styles.paragraph}>12 - Definitions</p>
          <p className={styles.paragraph}>Consequential Loss means, whether under statute, contract, equity, tort (including negligence), indemnity or otherwise; any loss or damage that cannot be considered to arise according to the usual course of things from the relevant breach, act or omission, whether or not such loss or damage may reasonably be supposed to have been in the contemplation of the Parties at the time they entered into these Terms as a probable result of the relevant breach, act or omission, and/or, any real or anticipated loss of profit, loss of benefit, loss of revenue, loss of business, loss of goodwill, loss of opportunity, loss of savings, loss of reputation, loss of use and/or loss or corruption of data. The Parties agree that your obligation to pay us the Price under these Terms will not constitute “Consequential Loss”.</p>
          <p className={styles.paragraph}>Force Majeure Event means any event or circumstance which is beyond a Party’s reasonable control.</p>
          <p className={styles.paragraph}>Liability means any expense, cost, liability, loss, damage, claim, notice, entitlement, investigation, demand, proceeding or judgment (whether under statute, contract, equity, tort (including negligence), indemnity or otherwise), howsoever arising, whether direct or indirect and/or whether present, unascertained, future or contingent and whether involving a third party or a party to these Terms or otherwise.</p>
          <p className={styles.paragraph}>Personnel mean any of our employees, consultants, suppliers, subcontractors or agents.</p>
          <p className={styles.paragraph}>13 - Contact details</p>
          <p className={styles.paragraph}>For questions, complaints, warranty claims and notices under these Terms, please contact us using the following details:</p>
          <p className={styles.paragraph}>Last updated: 2 September 2026</p>
        </div>
      </div>
      <Footer />
    </main>
  );
}
